inherit cmake pkgconfig

SUMMARY = "Qualcomm open-source GStreamer Plugins (Combined)"
SECTION = "multimedia"
LICENSE = "BSD-3-Clause-Clear"
LIC_FILES_CHKSUM = "file://${COMMON_LICENSE_DIR}/${LICENSE};md5=7a434440b651f4a472ca93716d01033a"

# Common dependencies
DEPENDS = "gstreamer1.0 gstreamer1.0-plugins-base virtual/kernel virtual/egl virtual/libgles2 json-glib cairo opencv hiredis libeigen mosquitto tensorflow-lite libsoup-2.4 gstreamer1.0-rtsp-server librdkafka"
DEPENDS:append:qcom-custom-bsp = " qcom-fastcv-binaries"
DEPENDS += "qcom-adreno gstreamer1.0-plugins-bad"

SRCREV = "${AUTOREV}"
PR = "r8"
FILESPATH =+ "${WORKSPACE}/:"

# Source and build configuration
SRC_URI = "file://gst-plugins-qti-oss/"
S = "${UNPACKDIR}/gst-plugins-qti-oss/"

# Install directories
INSTALL_INCDIR = "${includedir}"
INSTALL_BINDIR = "${bindir}"
INSTALL_LIBDIR = "${libdir}"

# Platform definitions
IMAGE_MAX_WIDTH = "4096"
IMAGE_MAX_HEIGHT = "4096"
VIDEO_MAX_WIDTH = "4096"
VIDEO_MAX_HEIGHT = "4096"
VIDEO_MAX_FPS = "120/1"
VIDEO_TYPE_SUPPORT = "TRUE"
MULTI_CAMERA_ENABLE = "FALSE"
EIS_MODES_ENABLE = "TRUE"
VHDR_MODES_ENABLE = "TRUE"
VIDEO_UYVY_FORMAT_ENABLE = "FALSE"
VIDEO_YUY2_FORMAT_ENABLE = "FALSE"
VIDEO_P010_10LE_FORMAT_ENABLE = "FALSE"
VIDEO_NV12_10LE32_FORMAT_ENABLE = "FALSE"
IMAGE_NV12_FORMAT_ENABLE = "FALSE"
FEATURE_LOGICAL_CAMERA_SUPPORT = "FALSE"
FEATURE_LOGICAL_CAMERA_SENSOR_SWITCH = "FALSE"
FEATURE_OFFLINE_IFE_SUPPORT = "TRUE"
FEATURE_SW_TNR = "TRUE"

# Encode/Decode/Display/ML variables
ENABLE_VIDEO_ENCODE = "TRUE"
ENABLE_VIDEO_DECODE = "TRUE"
ENABLE_DISPLAY = "TRUE"
ENABLE_ML = "TRUE"

# Platform-specific overrides
IMAGE_MAX_WIDTH:qcm6490 = "5184"
IMAGE_MAX_HEIGHT:qcm6490 = "3880"
VIDEO_MAX_WIDTH:qcm6490 = "5184"
VIDEO_MAX_HEIGHT:qcm6490 = "3880"

IMAGE_MAX_WIDTH:qcs9100 = "5184"
IMAGE_MAX_HEIGHT:qcs9100 = "3880"
VIDEO_MAX_WIDTH:qcs9100 = "5184"
VIDEO_MAX_HEIGHT:qcs9100 = "3880"

IMAGE_MAX_WIDTH:qcs8300 = "5184"
IMAGE_MAX_HEIGHT:qcs8300 = "3880"
VIDEO_MAX_WIDTH:qcs8300 = "5184"
VIDEO_MAX_HEIGHT:qcs8300 = "3880"

# Custom paths
CUSTOM_SYSROOT_PATH = "${WORKDIR}/build/gst-plugin-base/gst/utils:${WORKDIR}/build/gst-plugin-base/gst/video:${WORKDIR}/build/gst-plugin-base/gst/gfx:${WORKDIR}/build/gst-plugin-base/gst/allocators:${WORKDIR}/build/gst-plugin-base/gst/memory:${WORKDIR}/build/gst-plugin-base/gst/ml:${WORKDIR}/build/gst-plugin-base/gst/cv:${PKG_CONFIG_PATH}"

# Configure hook
do_configure:prepend() {
    export CFLAGS="${CFLAGS} -I${UNPACKDIR}/gst-plugins-qti-oss/gst-plugin-base"
    export CXXFLAGS="${CXXFLAGS} -I${UNPACKDIR}/gst-plugins-qti-oss/gst-plugin-base"
    export LDFLAGS="${LDFLAGS} -L${CUSTOM_SYSROOT_PATH}"
    export PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:${CUSTOM_SYSROOT_PATH}"
    
    mkdir -p ${UNPACKDIR}/gst-plugins-qti-oss/gst/sampleapps/
    cp ${UNPACKDIR}/gst-plugins-qti-oss/gst-sample-apps/gst-sample-apps-utils/*.h ${UNPACKDIR}/gst-plugins-qti-oss/gst/sampleapps/.
}

# Package configuration
PACKAGECONFIG[auto-framing] = "-DENABLE_TRACKING_CAM=true, -DENABLE_TRACKING_CAM=false, qti-auto-framing-stabilization, qti-auto-framing-stabilization"
ENABLE_WEBRTC = "TRUE"

# CMake options
EXTRA_OECMAKE = "\
    -DCAMERA_CLIENT_DISABLED=${CAMERA_CLIENT_DISABLED} \
    -DCODEC2_ENCODE=${CODEC2_ENCODE} \
    -DCAMERA_METADATA_VERSION=${CAMERA_METADATA_VERSION} \
    -DENABLE_WEBRTC=${ENABLE_WEBRTC} \
    -DGST_IMAGE_MAX_WIDTH=${IMAGE_MAX_WIDTH} \
    -DGST_IMAGE_MAX_HEIGHT=${IMAGE_MAX_HEIGHT} \
    -DCMAKE_INSTALL_PREFIX=${WORKSPACE}/usr \
    -DCMAKE_BUILD_TYPE=None \
    -DCMAKE_INSTALL_SYSCONFDIR=${WORKSPACE}/etc \
    -DCMAKE_INSTALL_LOCALSTATEDIR=${WORKSPACE}/var \
    -DCMAKE_INSTALL_RUNSTATEDIR=${WORKSPACE}/run \
    -DCMAKE_INSTALL_LIBDIR=${WORKSPACE}/lib/aarch64-linux-gnu \
    -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON \
    -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF \
    -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON \
    -DFETCHCONTENT_FULLY_DISCONNECTED=ON \
    -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON \
    -DCMAKE_VERBOSE_MAKEFILE=ON \
    -DGST_VIDEO_MAX_WIDTH=${VIDEO_MAX_WIDTH} \
    -DGST_VIDEO_MAX_HEIGHT=${VIDEO_MAX_HEIGHT} \
    -DGST_VIDEO_MAX_FPS=${VIDEO_MAX_FPS} \
    -DCAMERA_METADATA_VERSION=${CAMERA_METADATA_VERSION} \
    -DGST_VIDEO_TYPE_SUPPORT=${VIDEO_TYPE_SUPPORT} \
    -DGST_VERSION_REQUIRED=1.20.7 \
    -DSYSROOT_INCDIR='${UNPACKDIR}/gst-plugins-qti-oss/gst-plugin-base;${UNPACKDIR}/gst-plugins-qti-oss/' \
    -DSYSROOT_LIBDIR=${WORKSPACE}/usr/lib \
    -DKERNEL_BUILDDIR=${STAGING_INCDIR}/linux-msm \
    -DGST_PLUGINS_QTI_OSS_INSTALL_INCDIR=${INSTALL_INCDIR} \
    -DGST_PLUGINS_QTI_OSS_INSTALL_BINDIR=${INSTALL_BINDIR} \
    -DGST_PLUGINS_QTI_OSS_INSTALL_LIBDIR=${INSTALL_LIBDIR} \
    -DGST_PLUGINS_QTI_OSS_INSTALL_CONFIG=${WORKSPACE}/etc/configs \
    -DGST_PLUGINS_QTI_OSS_LICENSE=BSD \
    -DGST_PLUGINS_QTI_OSS_VERSION=${PV} \
    -DGST_PLUGINS_QTI_OSS_PACKAGE=${PN} \
    -DGST_PLUGINS_QTI_OSS_SUMMARY="${SUMMARY}" \
    -DGST_PLUGINS_QTI_OSS_ORIGIN=Unknown\ package\ origin \
"

# Plugin enable/disable options (matching original CMake)
GST_PLUGINS_QTI_OSS_ENABLE_BASE ?= "1"
GST_PLUGINS_QTI_OSS_ENABLE_QMMFSRC ?= "0"
GST_PLUGINS_QTI_OSS_ENABLE_VCOMPOSER ?= "1"
GST_PLUGINS_QTI_OSS_ENABLE_TOOLS ?= "1"
GST_PLUGINS_QTI_OSS_ENABLE_BATCH ?= "1"
GST_PLUGINS_QTI_OSS_ENABLE_METAMUX ?= "1"
GST_PLUGINS_QTI_OSS_ENABLE_SOCKET ?= "1"
GST_PLUGINS_QTI_OSS_ENABLE_VSPLIT ?= "1"
GST_PLUGINS_QTI_OSS_ENABLE_VTRANSFORM ?= "1"
GST_PLUGINS_QTI_OSS_ENABLE_VOVERLAY ?= "1"
GST_PLUGINS_QTI_OSS_ENABLE_RESTRICTED_ZONE ?= "1"
GST_PLUGINS_QTI_OSS_ENABLE_RTSPBIN ?= "1"
GST_PLUGINS_QTI_OSS_ENABLE_REDISSINK ?= "1"
GST_PLUGINS_QTI_OSS_ENABLE_SMARTVENCBIN ?= "0"
GST_PLUGINS_QTI_OSS_ENABLE_CAMREPROC ?= "0"
GST_PLUGINS_QTI_OSS_ENABLE_JPEGENC ?= "0"
GST_PLUGINS_QTI_OSS_ENABLE_VIDEOTEMPLATE ?= "1"

# ML Plugins
GST_PLUGINS_QTI_OSS_ENABLE_MLACONVERTER ?= "0"
GST_PLUGINS_QTI_OSS_ENABLE_MLACLASSIFICATION ?= "0"
GST_PLUGINS_QTI_OSS_ENABLE_MLDEMUX ?= "1"
GST_PLUGINS_QTI_OSS_ENABLE_MLVCONVERTER ?= "1"
GST_PLUGINS_QTI_OSS_ENABLE_MLVCLASSIFICATION ?= "1"
GST_PLUGINS_QTI_OSS_ENABLE_MLVSUPERRESOLUTION ?= "1"
GST_PLUGINS_QTI_OSS_ENABLE_MLVDISCOVERY ?= "1"
GST_PLUGINS_QTI_OSS_ENABLE_MLVPOSE ?= "1"
GST_PLUGINS_QTI_OSS_ENABLE_MLVSEGMENTATION ?= "1"
GST_PLUGINS_QTI_OSS_ENABLE_MLTOOLS ?= "1"
GST_PLUGINS_QTI_OSS_ENABLE_MLTFLITE ?= "0"
GST_PLUGINS_QTI_OSS_ENABLE_MLSNPE ?= "0"
GST_PLUGINS_QTI_OSS_ENABLE_MLQNN ?= "0"
GST_PLUGINS_QTI_OSS_ENABLE_MLMETAPARSER ?= "1"
GST_PLUGINS_QTI_OSS_ENABLE_METATRANSFORM ?= "1"
GST_PLUGINS_QTI_OSS_ENABLE_OBJTRACKER ?= "0"
GST_PLUGINS_QTI_OSS_ENABLE_MLMETAEXTRACTOR ?= "1"
GST_PLUGINS_QTI_OSS_ENABLE_MLPOSTPROCESS ?= "1"

# Sample Apps and Test Framework
GST_PLUGINS_QTI_OSS_ENABLE_SAMPLE_APPS_UTILS ?= "1"
GST_PLUGINS_QTI_OSS_ENABLE_SAMPLE_APPS ?= "1"
GST_PLUGINS_QTI_OSS_ENABLE_TEST_FRAMEWORK ?= "0"
GST_PLUGINS_QTI_OSS_ENABLE_PYTHON_EXAMPLES ?= "1"

# Messaging Plugins
GST_PLUGINS_QTI_OSS_ENABLE_MSGBROKER ?= "1"

# Non-QLI Plugins
GST_PLUGINS_QTI_OSS_ENABLE_NON_QLI ?= "0"
GST_PLUGINS_QTI_OSS_ENABLE_CODEC2 ?= "0"
GST_PLUGINS_QTI_OSS_ENABLE_CV_IMGPIRAMID ?= "0"
GST_PLUGINS_QTI_OSS_ENABLE_CV_OPTCLFLOW ?= "0"
GST_PLUGINS_QTI_OSS_ENABLE_DFS ?= "0"
GST_PLUGINS_QTI_OSS_ENABLE_DRMDECRYPTOR ?= "0"
GST_PLUGINS_QTI_OSS_ENABLE_MLAIC ?= "0"
GST_PLUGINS_QTI_OSS_ENABLE_EXAMPLES ?= "0"

# Add plugin-specific CMake options
EXTRA_OECMAKE += "\
    -DENABLE_GST_PLUGIN_BASE=${GST_PLUGINS_QTI_OSS_ENABLE_BASE} \
    -DENABLE_GST_PLUGIN_QMMFSRC=${GST_PLUGINS_QTI_OSS_ENABLE_QMMFSRC} \
    -DENABLE_GST_PLUGIN_VCOMPOSER=${GST_PLUGINS_QTI_OSS_ENABLE_VCOMPOSER} \
    -DENABLE_GST_PLUGIN_TOOLS=${GST_PLUGINS_QTI_OSS_ENABLE_TOOLS} \
    -DENABLE_GST_PLUGIN_BATCH=${GST_PLUGINS_QTI_OSS_ENABLE_BATCH} \
    -DENABLE_GST_PLUGIN_METAMUX=${GST_PLUGINS_QTI_OSS_ENABLE_METAMUX} \
    -DENABLE_GST_PLUGIN_SOCKET=${GST_PLUGINS_QTI_OSS_ENABLE_SOCKET} \
    -DENABLE_GST_PLUGIN_VSPLIT=${GST_PLUGINS_QTI_OSS_ENABLE_VSPLIT} \
    -DENABLE_GST_PLUGIN_VTRANSFORM=${GST_PLUGINS_QTI_OSS_ENABLE_VTRANSFORM} \
    -DENABLE_GST_PLUGIN_VOVERLAY=${GST_PLUGINS_QTI_OSS_ENABLE_VOVERLAY} \
    -DENABLE_GST_PLUGIN_RESTRICTED_ZONE=${GST_PLUGINS_QTI_OSS_ENABLE_RESTRICTED_ZONE} \
    -DENABLE_GST_PLUGIN_RTSPBIN=${GST_PLUGINS_QTI_OSS_ENABLE_RTSPBIN} \
    -DENABLE_GST_PLUGIN_REDISSINK=${GST_PLUGINS_QTI_OSS_ENABLE_REDISSINK} \
    -DENABLE_GST_PLUGIN_SMARTVENCBIN=${GST_PLUGINS_QTI_OSS_ENABLE_SMARTVENCBIN} \
    -DENABLE_GST_PLUGIN_CAMREPROC=${GST_PLUGINS_QTI_OSS_ENABLE_CAMREPROC} \
    -DENABLE_GST_PLUGIN_JPEGENC=${GST_PLUGINS_QTI_OSS_ENABLE_JPEGENC} \
    -DENABLE_GST_PLUGIN_VIDEOTEMPLATE=${GST_PLUGINS_QTI_OSS_ENABLE_VIDEOTEMPLATE} \
    -DENABLE_GST_PLUGIN_MLACONVERTER=${GST_PLUGINS_QTI_OSS_ENABLE_MLACONVERTER} \
    -DENABLE_GST_PLUGIN_MLACLASSIFICATION=${GST_PLUGINS_QTI_OSS_ENABLE_MLACLASSIFICATION} \
    -DENABLE_GST_PLUGIN_MLDEMUX=${GST_PLUGINS_QTI_OSS_ENABLE_MLDEMUX} \
    -DENABLE_GST_PLUGIN_MLVCONVERTER=${GST_PLUGINS_QTI_OSS_ENABLE_MLVCONVERTER} \
    -DENABLE_GST_PLUGIN_MLVCLASSIFICATION=${GST_PLUGINS_QTI_OSS_ENABLE_MLVCLASSIFICATION} \
    -DENABLE_GST_PLUGIN_MLVSUPERRESOLUTION=${GST_PLUGINS_QTI_OSS_ENABLE_MLVSUPERRESOLUTION} \
    -DENABLE_GST_PLUGIN_MLVDISCOVERY=${GST_PLUGINS_QTI_OSS_ENABLE_MLVDISCOVERY} \
    -DENABLE_GST_PLUGIN_MLVPOSE=${GST_PLUGINS_QTI_OSS_ENABLE_MLVPOSE} \
    -DENABLE_GST_PLUGIN_MLVSEGMENTATION=${GST_PLUGINS_QTI_OSS_ENABLE_MLVSEGMENTATION} \
    -DENABLE_GST_PLUGIN_MLTOOLS=${GST_PLUGINS_QTI_OSS_ENABLE_MLTOOLS} \
    -DENABLE_GST_PLUGIN_MLTFLITE=${GST_PLUGINS_QTI_OSS_ENABLE_MLTFLITE} \
    -DENABLE_GST_PLUGIN_MLSNPE=${GST_PLUGINS_QTI_OSS_ENABLE_MLSNPE} \
    -DENABLE_GST_PLUGIN_MLQNN=${GST_PLUGINS_QTI_OSS_ENABLE_MLQNN} \
    -DENABLE_GST_PLUGIN_MLMETAPARSER=${GST_PLUGINS_QTI_OSS_ENABLE_MLMETAPARSER} \
    -DENABLE_GST_PLUGIN_METATRANSFORM=${GST_PLUGINS_QTI_OSS_ENABLE_METATRANSFORM} \
    -DENABLE_GST_PLUGIN_OBJTRACKER=${GST_PLUGINS_QTI_OSS_ENABLE_OBJTRACKER} \
    -DENABLE_GST_PLUGIN_MLMETAEXTRACTOR=${GST_PLUGINS_QTI_OSS_ENABLE_MLMETAEXTRACTOR} \
    -DENABLE_GST_PLUGIN_MLPOSTPROCESS=${GST_PLUGINS_QTI_OSS_ENABLE_MLPOSTPROCESS} \
    -DENABLE_GST_SAMPLE_APPS_UTILS=${GST_PLUGINS_QTI_OSS_ENABLE_SAMPLE_APPS_UTILS} \
    -DENABLE_GST_SAMPLE_APPS=${GST_PLUGINS_QTI_OSS_ENABLE_SAMPLE_APPS} \
    -DENABLE_GST_TEST_FRAMEWORK=${GST_PLUGINS_QTI_OSS_ENABLE_TEST_FRAMEWORK} \
    -DENABLE_GST_PYTHON_EXAMPLES=${GST_PLUGINS_QTI_OSS_ENABLE_PYTHON_EXAMPLES} \
    -DENABLE_GST_PLUGIN_MSGBROKER=${GST_PLUGINS_QTI_OSS_ENABLE_MSGBROKER} \
    -DENABLE_NON_QLI=${GST_PLUGINS_QTI_OSS_ENABLE_NON_QLI} \
"

# Package configuration
PACKAGECONFIG = "${@bb.utils.contains('PREFERRED_PROVIDER_virtual/libgbm', 'gbm', 'gbm', '', d)}"
PACKAGECONFIG[gbm] = " , ,gbm,gbm"

# File management
FILES:${PN} += "${INSTALL_BINDIR} ${INSTALL_LIBDIR}"
FILES:${PN}-dbg += "${INSTALL_LIBDIR}/gstreamer-1.0/.debug"
SOLIBS = ".so*"
FILES_SOLIBSDEV = ""
INSANE_SKIP:${PN} = "dev-so"

# Runtime dependencies
RDEPENDS:${PN} = "\
    gstreamer1.0 \
    gstreamer1.0-plugins-base \
"